### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Pok09** [patrickcate/nuxt-jsonapi#247]
Doen't work :

```
Nuxt: 3.4.3 
Nitro: 2.3.3
```

```
Cannot read properties of undefined (reading 'public')

at wrapper (C:\laragon\www\flex\app\node_modules\.pnpm\nuxt@3.4.3_@types+node@18.0.0\node_modules\nuxt\dist\app\nuxt.js:198:21)
at C:\laragon\www\flex\app\virtual:nuxt:C:\laragon\www\flex\app\.nuxt\plugins\server.mjs:31:80
at Module.executeAsync (/C:/laragon/www/flex/app/node_modules/.pnpm/unctx@2.3.0/node_modules/unctx/dist/index.mjs:111:19)
at Object.setup (C:\laragon\www\flex\app\virtual:nuxt:C:\laragon\www\flex\app\.nuxt\plugins\server.mjs:31:63)
at wrapper (C:\laragon\www\flex\app\node_modules\.pnpm\nuxt@3.4.3_@types+node@18.0.0\node_modules\nuxt\dist\app\nuxt.js:198:21)
at fn (C:\laragon\www\flex\app\node_modules\.pnpm\nuxt@3.4.3_@types+node@18.0.0\node_modules\nuxt\dist\app\nuxt.js:214:27)
at Object.callAsync (/C:/laragon/www/flex/app/node_modules/.pnpm/unctx@2.3.0/node_modules/unctx/dist/index.mjs:68:55)
at callWithNuxt (C:\laragon\www\flex\app\node_modules\.pnpm\nuxt@3.4.3_@types+node@18.0.0\node_modules\nuxt\dist\app\nuxt.js:216:23)
at applyPlugin (C:\laragon\www\flex\app\node_modules\.pnpm\nuxt@3.4.3_@types+node@18.0.0\node_modules\nuxt\dist\app\nuxt.js:129:29)
```

**Comment by ricovandevin** [comment]
I'm experiencing the same issue.

```
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'public')                                                                                          3:45:11 PM
  at Object.setup (./node_modules/nuxt-jsonapi/dist/runtime/plugin.mjs:6:55)  
  at wrapper (./node_modules/nuxt/dist/app/nuxt.js:198:21)  
  at fn (./node_modules/nuxt/dist/app/nuxt.js:214:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:55)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.js:216:23)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.js:129:29)  
  at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.js:139:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.js:29:7)  
  at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
```

Nuxt version 3.4.3.

**Comment by ricovandevin** [comment]
The issue seems to be that `nuxtApp.payload.config` is not set on the server side. Settings `ssr: false` in the Nuxt config gets rid of the error. This might work as a temporary workaround.

**Comment by Pok09** [comment]
> The issue seems to be that `nuxtApp.payload.config` is not set on the server side. Settings `ssr: false` in the Nuxt config gets rid of the error. This might work as a temporary workaround.

doesn't work for me

**Comment by patrickcate** [comment]
I can confirm the issue and am investigating. It is related to some change in Nuxt `3.4.0`. Downgrading to `3.3.3` should work as a temporary workaround.

**Comment by patrickcate** [comment]
I just released version `2.0.2` which should fix this issue.

**Comment by ricovandevin** [comment]
I can confirm that the issue is fixed in version 2.0.2. Thanks for the fast response @patrickcate !

**Comment by Pok09** [comment]
> 🎉 This issue has been resolved in version 2.0.2 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/nuxt-jsonapi/v/2.0.2)
> * [GitHub release](https://github.com/patrickcate/nuxt-jsonapi/releases/tag/v2.0.2)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Great, no error now
Thanks for the fast response

**Comment by Pok09** [comment]
...

**Comment by Pok09** [comment]
this issue can be close
